### ISSUE TITLE
About the Networt of TSN

### ISSUE THREAD

**Issue by linshuheng6** [shuangshuangguo/caffe2pytorch-tsn#20]
Hi, thank you for your work.

I tried to use your pre-trained model and I set the Arch as BNInception. However, there was something wrong that it shows size mismatch.

I want to know when you train this model, whether the parameter 'arch' is BNInception?

Thank you

**Comment by linshuheng6** [comment]
I have solved it.!

**Comment by xianyuanliu** [comment]
Hi, 
I met the same problem. Could you please tell me how to solve it? Thanks.

**Comment by shuangshuangguo** [comment]
You should show the clear error message, if not, I can not figure it out.

**Comment by xianyuanliu** [comment]
Thanks for the reply! I have solved it which is caused by different PyTorch version.
