### ISSUE TITLE
Accuracy on Kinetics

### ISSUE THREAD

**Issue by Shumpei-Kikuta** [shuangshuangguo/caffe2pytorch-tsn#22]
Thank you for your great work!

You provide us with the pretrained model on Kinetics400, which is so helpful.
I was wondering about the accuracy the model performs.
Can you tell us the accuracy in README?

Thank you in advance.

**Comment by shuangshuangguo** [comment]
Sorry, I do not have Kinetics dataset, so accuracy on Kinetics is not provided.
