### ISSUE TITLE
convert t7 to pth problem

### ISSUE THREAD

**Issue by FingerRec** [shuangshuangguo/caffe2pytorch-tsn#4]
finally transfer torchmodel to pytorchmodel
Traceback (most recent call last):
  File "convert_torch.py", line 140, in <module>
    torch_to_pytorch(model, output)
  File "convert_torch.py", line 134, in torch_to_pytorch
    lua_recursive_model(model,n)
  File "convert_torch.py", line 70, in lua_recursive_model
    add_submodule(names, seq, n)
  File "convert_torch.py", line 54, in add_submodule
    seq.add_module(names,n)
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/modules/module.py", line 169, in add_module
    raise KeyError("module name can't contain \".\"")
KeyError: 'module name can\'t contain "."'

I solved it by change
`names = 'base_model.' + names.replace('/', '_');`
into
`
names = 'base_model' + names.replace('/', '_');`
in several lines in convert_torch.py

**Comment by FingerRec** [comment]
It seems this website's  module [yjxiong-kinetics_action](http://yjxiong.me/others/kinetics_action/) is the same as TSN's Caffe Model in this project. The weight should be use directly. But as i use **this useful project** to convert it to pyTorch, the following problem happens.

then get torchmodel:
/usr/local/bin/luajit: /usr/local/share/lua/5.1/hdf5/group.lua:327: HDF5Group:read() - no such child 'conv1' for [HDF5Group 33554432 /]
stack traceback:
	[C]: in function 'error'
	/usr/local/share/lua/5.1/hdf5/group.lua:327: in function 'read'
	googlenet.lua:151: in main chunk
	[C]: in function 'dofile'
	/usr/local/lib/luarocks/rocks/trepl/scm-1/bin/th:150: in main chunk
	[C]: at 0x00405050
/usr/local/bin/luajit: /usr/local/share/lua/5.1/hdf5/group.lua:327: HDF5Group:read() - no such child 'conv1' for [HDF5Group 33554432 /]
stack traceback:
	[C]: in function 'error'
	/usr/local/share/lua/5.1/hdf5/group.lua:327: in function 'read'
	googlenet.lua:151: in main chunk
	[C]: in function 'dofile'
	/usr/local/lib/luarocks/rocks/trepl/scm-1/bin/th:150: in main chunk
	[C]: at 0x00405050

looking forward to your reply, thanks

**Comment by shuangshuangguo** [comment]
You should replace '/' with '_' in googlenet.lua.
For example, in line 9, you should modify it as follows:
a1x1.name = name .. '_1x1'
And 'fc-action' should be modified to 'fc_action'
This maybe because the author modified the layer name.

I will update the code soon. Thanks for your attention.

**Comment by FingerRec** [comment]
Thanks for your reply a lot!  googlenet_kinetics.lua works well.

I find in the new version torch,**' .'s are no longer allowed in module keys.** (I install it a few days ago )
[pytorch-issues-6941](https://github.com/pytorch/pytorch/issues/6941)
[pytorch-vision-pull-474](https://github.com/pytorch/vision/pull/474)

so i used a older version(0.3.1),and get the .pth.

but as i add the pth ,
`checkpoint = torch.load("pretrained_model/kinetics_1_flow.pth")`

The follow problem happened.
 base_dict.setdefault('new_fc.weight', checkpoint['base_model.fc-action.1.weight'])
KeyError: 'base_model.fc-action.1.weight'

Looking forward to your reply, thanks .

**Comment by shuangshuangguo** [comment]
For kinetics dataset, you should replace 'fc-action' with 'fc_action'.
That is to say,
base_dict.setdefault('new_fc.weight', checkpoint['base_model.fc_action.1.weight'])
base_dict.setdefault('new_fc.bias', checkpoint['base_model.fc_action.1.bias'])

**Comment by FingerRec** [comment]
get it, thanks~

**Comment by shuangshuangguo** [comment]
And if you want to use the newest version of pytorch, you can modify my code easily. Just modify the dict key should work.
