### ISSUE TITLE
Weird accuracy on UCF101 split 2 and 3

### ISSUE THREAD

**Issue by xwying** [shuangshuangguo/caffe2pytorch-tsn#6]
Hi, I tried to use your converted weight to run the evaluation on the UCF101 dataset. On split 1, I got a reasonable accuracy close to the paper as you described. However, on split 2 and 3, the resulting accuracies given by the test_model.py are all 100.00% (both RGB and Flow), which is really strange.

Have you ever tried to evaluate the second and the third splits? If so, may I know what accuracy you've got?

**Comment by shuangshuangguo** [comment]
The model I give  is trained on the split 1 training set, so it's only used to test on split 1 testing set. If you want to test on the split 2 or split 3, you must use the corresponding models trained on split 2 or split 3.

**Comment by xwying** [comment]
Ah, I forgot the fact that each split has its own training set. Thanks for your answer!

**Comment by szu-lqt** [comment]
@shuangshuangguo  Hi，I tried to use your  converted weight "ucf101_rgb.pth" to run the evaluation on the UCF101 dataset on split 1 (the command " python test_models.py ucf101 RGB ucf101_rgb_val_list.txt ucf101_bninception_rgb_checkpoint.pth --arch BNInception --save_scores my_score_file"),  I run your test_models.py but I get the error "out of memory",so I modify something ,add "devices = list([0,1])" after line 103 in test_models.py, but, the new question I meet, I find the list var of cls_hit and  cls_cnt  are 102d, and the first dimension are zero, why they are not 101d? at the same time, the value in cls_hit list are almost zero, so I get the Accuracy only 0.51%, that's too low.  could you please give me some  advice?? Thanks!

**Comment by shuangshuangguo** [comment]
@szu-lqt Sorry, I have no idea. Maybe you should check test_models.py code.

**Comment by szu-lqt** [comment]
@shuangshuangguo Can I add your WeChat or QQ? My WeChat ID is lqt162636 or QQ 1253955013
